version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: jokesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  pgdata:
